services:
  frontend:
    build:
      context: frontend
    environment:
      VITE_API_ORIGIN: http://localhost/api
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  backend:
    restart: always
    build:
      context: backend
    environment:
      PORT: 3000
      DB_ADDRESS: mongodb://127.0.0.1:27017/weblarek?authSource=admin
      UPLOAD_PATH: images
      UPLOAD_PATH_TEMP: temp
      ORIGIN_ALLOW: http://localhost:5173
      AUTH_REFRESH_TOKEN_EXPIRY: 10y
      AUTH_ACCESS_TOKEN_EXPIRY: 10y
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    ports:
      - 3000:3000
    networks:
      - internal
    depends_on:
      - mongo

  server:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  frontend:
  public:
  db:

networks:
  internal: